name: movies_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  dio: ^5.4.2+1
  flutter_screenutil: ^5.9.0
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  dartz: ^0.10.1
  equatable: ^2.0.5
  freezed: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9


  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/

